// flow-typed signature: b8460f9db9719216640adffd863ef1c9
// flow-typed version: <<STUB>>/cypress-image-snapshot_v3.1.1/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-image-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-image-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-image-snapshot/command' {
  declare module.exports: any;
}

declare module 'cypress-image-snapshot/constants' {
  declare module.exports: any;
}

declare module 'cypress-image-snapshot/plugin' {
  declare module.exports: any;
}

declare module 'cypress-image-snapshot/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-image-snapshot/command.js' {
  declare module.exports: $Exports<'cypress-image-snapshot/command'>;
}
declare module 'cypress-image-snapshot/constants.js' {
  declare module.exports: $Exports<'cypress-image-snapshot/constants'>;
}
declare module 'cypress-image-snapshot/plugin.js' {
  declare module.exports: $Exports<'cypress-image-snapshot/plugin'>;
}
declare module 'cypress-image-snapshot/reporter.js' {
  declare module.exports: $Exports<'cypress-image-snapshot/reporter'>;
}
