// flow-typed signature: d1877919b0dba501eb5a834be0029f20
// flow-typed version: <<STUB>>/react-fast-compare_v^2.0.4/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fast-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fast-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-fast-compare/index' {
  declare module.exports: $Exports<'react-fast-compare'>;
}
declare module 'react-fast-compare/index.js' {
  declare module.exports: $Exports<'react-fast-compare'>;
}
