// flow-typed signature: 0f7810959d06459ab700c75083bf8af3
// flow-typed version: <<STUB>>/release-it_v12.4.3/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'release-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'release-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'release-it/bin/release-it' {
  declare module.exports: any;
}

declare module 'release-it/lib/breaking' {
  declare module.exports: any;
}

declare module 'release-it/lib/cli' {
  declare module.exports: any;
}

declare module 'release-it/lib/config' {
  declare module.exports: any;
}

declare module 'release-it/lib/deprecated' {
  declare module.exports: any;
}

declare module 'release-it/lib/errors' {
  declare module.exports: any;
}

declare module 'release-it/lib' {
  declare module.exports: any;
}

declare module 'release-it/lib/log' {
  declare module.exports: any;
}

declare module 'release-it/lib/metrics' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/factory' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/git/Git' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/git/prompts' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/GitBase' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/github/GitHub' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/github/prompts' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/gitlab/GitLab' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/gitlab/prompts' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/GitRelease' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/npm/npm' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/npm/prompts' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/Plugin' {
  declare module.exports: any;
}

declare module 'release-it/lib/plugin/version/Version' {
  declare module.exports: any;
}

declare module 'release-it/lib/prompt' {
  declare module.exports: any;
}

declare module 'release-it/lib/shell' {
  declare module.exports: any;
}

declare module 'release-it/lib/spinner' {
  declare module.exports: any;
}

declare module 'release-it/lib/tasks' {
  declare module.exports: any;
}

declare module 'release-it/lib/util' {
  declare module.exports: any;
}

declare module 'release-it/test/stub/github' {
  declare module.exports: any;
}

declare module 'release-it/test/stub/gitlab' {
  declare module.exports: any;
}

declare module 'release-it/test/stub/shell' {
  declare module.exports: any;
}

declare module 'release-it/test/util/helpers' {
  declare module.exports: any;
}

declare module 'release-it/test/util' {
  declare module.exports: any;
}

declare module 'release-it/test/util/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'release-it/bin/release-it.js' {
  declare module.exports: $Exports<'release-it/bin/release-it'>;
}
declare module 'release-it/lib/breaking.js' {
  declare module.exports: $Exports<'release-it/lib/breaking'>;
}
declare module 'release-it/lib/cli.js' {
  declare module.exports: $Exports<'release-it/lib/cli'>;
}
declare module 'release-it/lib/config.js' {
  declare module.exports: $Exports<'release-it/lib/config'>;
}
declare module 'release-it/lib/deprecated.js' {
  declare module.exports: $Exports<'release-it/lib/deprecated'>;
}
declare module 'release-it/lib/errors.js' {
  declare module.exports: $Exports<'release-it/lib/errors'>;
}
declare module 'release-it/lib/index' {
  declare module.exports: $Exports<'release-it/lib'>;
}
declare module 'release-it/lib/index.js' {
  declare module.exports: $Exports<'release-it/lib'>;
}
declare module 'release-it/lib/log.js' {
  declare module.exports: $Exports<'release-it/lib/log'>;
}
declare module 'release-it/lib/metrics.js' {
  declare module.exports: $Exports<'release-it/lib/metrics'>;
}
declare module 'release-it/lib/plugin/factory.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/factory'>;
}
declare module 'release-it/lib/plugin/git/Git.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/git/Git'>;
}
declare module 'release-it/lib/plugin/git/prompts.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/git/prompts'>;
}
declare module 'release-it/lib/plugin/GitBase.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/GitBase'>;
}
declare module 'release-it/lib/plugin/github/GitHub.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/github/GitHub'>;
}
declare module 'release-it/lib/plugin/github/prompts.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/github/prompts'>;
}
declare module 'release-it/lib/plugin/gitlab/GitLab.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/gitlab/GitLab'>;
}
declare module 'release-it/lib/plugin/gitlab/prompts.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/gitlab/prompts'>;
}
declare module 'release-it/lib/plugin/GitRelease.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/GitRelease'>;
}
declare module 'release-it/lib/plugin/npm/npm.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/npm/npm'>;
}
declare module 'release-it/lib/plugin/npm/prompts.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/npm/prompts'>;
}
declare module 'release-it/lib/plugin/Plugin.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/Plugin'>;
}
declare module 'release-it/lib/plugin/version/Version.js' {
  declare module.exports: $Exports<'release-it/lib/plugin/version/Version'>;
}
declare module 'release-it/lib/prompt.js' {
  declare module.exports: $Exports<'release-it/lib/prompt'>;
}
declare module 'release-it/lib/shell.js' {
  declare module.exports: $Exports<'release-it/lib/shell'>;
}
declare module 'release-it/lib/spinner.js' {
  declare module.exports: $Exports<'release-it/lib/spinner'>;
}
declare module 'release-it/lib/tasks.js' {
  declare module.exports: $Exports<'release-it/lib/tasks'>;
}
declare module 'release-it/lib/util.js' {
  declare module.exports: $Exports<'release-it/lib/util'>;
}
declare module 'release-it/test/stub/github.js' {
  declare module.exports: $Exports<'release-it/test/stub/github'>;
}
declare module 'release-it/test/stub/gitlab.js' {
  declare module.exports: $Exports<'release-it/test/stub/gitlab'>;
}
declare module 'release-it/test/stub/shell.js' {
  declare module.exports: $Exports<'release-it/test/stub/shell'>;
}
declare module 'release-it/test/util/helpers.js' {
  declare module.exports: $Exports<'release-it/test/util/helpers'>;
}
declare module 'release-it/test/util/index' {
  declare module.exports: $Exports<'release-it/test/util'>;
}
declare module 'release-it/test/util/index.js' {
  declare module.exports: $Exports<'release-it/test/util'>;
}
declare module 'release-it/test/util/setup.js' {
  declare module.exports: $Exports<'release-it/test/util/setup'>;
}
